### ISSUE TITLE
Update to use Shared AppVeyor module

### ISSUE THREAD

**Issue by PlagueHO** [PlagueHO/SystemLocaleDsc#11]

**Comment by PlagueHO** [comment]
Hi @kwirkykat or @zjalexander - I'm a maintainer of this repo, but I don't think I've got the permissions to the repo. Any chance you could grant them to me? No rush.

**Comment by kwirkykat** [comment]
@PlagueHO Done

**Comment by PlagueHO** [comment]
Thanks @kwirkykat
