### ISSUE TITLE
Combine SystemLocaleDsc Resource with ComputerManagementDsc 

### ISSUE THREAD

**Issue by PlagueHO** [PlagueHO/SystemLocaleDsc#14]
As we are converting xComputerManagement over to ComputerManagementDsc in the near future I thought it might be worth considering moving SystemLocaleDsc into ComputerManagementDsc at the same time. There has been some discussion around this in the past - see https://github.com/PowerShell/xComputerManagement/issues/50

@kwirkykat - do you have any thoughts on this? I'm happy to keep them separate but I thought it might simplify things as these "individual" resources make more sense together.

**Comment by kwirkykat** [comment]
@PlagueHO I like combining them 👍

**Comment by PlagueHO** [comment]
Coolo! 💯 I'll plan to do this at just prior to conversion to ComputerManagementDsc.
