### ISSUE TITLE
$IsSingleInstance purpose ?

### ISSUE THREAD

**Issue by ArieHein** [PlagueHO/SystemLocaleDsc#6]
Whats the purpose of $IsSingleInstance

its never used in any of the Get, Set, Test functions.

Theres no documentation on Get-WinSystemLocale  or Set-WinSystemLocale that mentions requiring additional parameters.

**Comment by PlagueHO** [comment]
This is the standard DSC resource design pattern that is used for resources that can only ever be applied once to a single node. This parameter acts as a surrogate key for the resource. Just set the value to yes as per the documentation. 

The pattern is documented in the DSCresources repo.

**Comment by PlagueHO** [comment]
Correction: the pattern is documented in docs.microsoft.com:

(updated) https://docs.microsoft.com/en-us/powershell/scripting/dsc/resources/singleInstance

**Comment by ArieHein** [comment]
Ok, I understand the necessity as its basically meta data and has no relevance to the code behavior rather the mof compiling and setting the waning appropriately. I'm assuming resources that dont have IsSingleInstance , the default is 'False' but can be omitted so compiling the mof doesn't break.
At least until all resources are converted to use that parameter with a default of 'False'.

Although i find it extremely strange you need to define it as a parameter
when we dont even use the value of $IsSingleInstance at all but its hardcoded in:

```
$returnValue = @{
    TimeZone = $CurrentTimeZone
    IsSingleInstance = 'Yes'
}
```

would be much more logical to use

```
$returnValue = @{
    TimeZone = $CurrentTimeZone
    IsSingleInstance = $IsSingleInstance 
```

 }

so if in the future if they do implement a default $IsSingleInstance = False, you wont have to change the value of the $returnValue.

**Comment by PlagueHO** [comment]
@ArieHein - Ah right - I see what you mean. Good point. I'll make the change.

**Comment by fullenw1** [comment]
I am just wondering about the purpose of **Yes**.

We already use **True/False** everywhere.

Using a new type of value could lead some to use it more often in other modules and create unnecessary confusion: "Should I use **Yes/No** or **True/False**?"

I know I am coming a bit late, and probably too late to change things...
But like I said, I am just wondering :-)

By the way, the link you mentioned is now broken:
https://msdn.microsoft.com/en-us/powershell/dsc/singleinstance

**Comment by PlagueHO** [comment]
Hi @fullenw1 - you should use a [System.Boolean] ($true/$false) for boolean parameters.

The IsSingleInstance is a pattern designed to handle a very specific situation as documented in the (corrected) link below. So, try not to think of IsSingleInstance as a 'yes/no' - because it can never be 'no'. It MUST always be 'yes' - and will not accept any other value (it will fail to compile).

Here is the updated link (MSDN is no more):
https://docs.microsoft.com/en-us/powershell/scripting/dsc/resources/singleInstance

**Comment by fullenw1** [comment]
Thanks for the explanation and the link, very instructive by the way :-)
